import type {IdentityAdapter,IdentityProvider} from "./index.js";
type Config={clientId:string;clientSecret:string};
const enc=(x:Record<string,string>)=>new URLSearchParams(x).toString();
async function json(url:string,init?:RequestInit){const r=await fetch(url,init);if(!r.ok)throw new Error(`OAuth HTTP ${r.status}`);return r.json() as Promise<any>}
export function oauthAdapter(provider:IdentityProvider,c:Config):IdentityAdapter{
if(provider==="google")return{provider,async authorizationUrl(state,redirectUri){return "https://accounts.google.com/o/oauth2/v2/auth?"+enc({client_id:c.clientId,redirect_uri:redirectUri,response_type:"code",scope:"openid email profile",state})},async exchangeCode(code,redirectUri){const t=await json("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:enc({client_id:c.clientId,client_secret:c.clientSecret,code,redirect_uri:redirectUri,grant_type:"authorization_code"})});const u=await json("https://openidconnect.googleapis.com/v1/userinfo",{headers:{authorization:`Bearer ${t.access_token}`}});return{subject:String(u.sub),email:u.email,displayName:u.name}}};
if(provider==="github")return{provider,async authorizationUrl(state,redirectUri){return "https://github.com/login/oauth/authorize?"+enc({client_id:c.clientId,redirect_uri:redirectUri,scope:"read:user user:email",state})},async exchangeCode(code,redirectUri){const t=await json("https://github.com/login/oauth/access_token",{method:"POST",headers:{accept:"application/json","content-type":"application/x-www-form-urlencoded"},body:enc({client_id:c.clientId,client_secret:c.clientSecret,code,redirect_uri:redirectUri})});const u=await json("https://api.github.com/user",{headers:{authorization:`Bearer ${t.access_token}`,"user-agent":"RECIPRA"}});return{subject:String(u.id),email:u.email,displayName:u.name??u.login}}};
if(provider==="meta")return{provider,async authorizationUrl(state,redirectUri){return "https://www.facebook.com/v23.0/dialog/oauth?"+enc({client_id:c.clientId,redirect_uri:redirectUri,state,scope:"email,public_profile"})},async exchangeCode(code,redirectUri){const t=await json("https://graph.facebook.com/v23.0/oauth/access_token?"+enc({client_id:c.clientId,client_secret:c.clientSecret,redirect_uri:redirectUri,code}));const u=await json("https://graph.facebook.com/me?"+enc({fields:"id,name,email",access_token:t.access_token}));return{subject:String(u.id),email:u.email,displayName:u.name}}};
return{provider,async authorizationUrl(state,redirectUri){return "https://x.com/i/oauth2/authorize?"+enc({response_type:"code",client_id:c.clientId,redirect_uri:redirectUri,scope:"users.read tweet.read offline.access",state,code_challenge:"configure-pkce-at-edge",code_challenge_method:"plain"})},async exchangeCode(){throw new Error("X OAuth requires PKCE verifier persistence; adapter intentionally gated until configured")}};
}