BEGIN;
CREATE SCHEMA IF NOT EXISTS core; CREATE SCHEMA IF NOT EXISTS identity; CREATE SCHEMA IF NOT EXISTS tenant; CREATE SCHEMA IF NOT EXISTS affiliate; CREATE SCHEMA IF NOT EXISTS tracking; CREATE SCHEMA IF NOT EXISTS referral; CREATE SCHEMA IF NOT EXISTS ledger; CREATE SCHEMA IF NOT EXISTS payment; CREATE SCHEMA IF NOT EXISTS module; CREATE SCHEMA IF NOT EXISTS privacy; CREATE SCHEMA IF NOT EXISTS governance; CREATE SCHEMA IF NOT EXISTS ai; CREATE SCHEMA IF NOT EXISTS evidence; CREATE SCHEMA IF NOT EXISTS audit;
COMMIT;
